server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 421622000950-e29jb4bvdouok8o3rdqsa43rr5d2mpdj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: pY7B4amaWwRMSLFPjUKA
            client-secret: Eatkn3VT5V
            client-name: Naver
            authorization-grant-type: authorization-code
            redirect-uri: http://localhost:8080/login/oauth/code/naver
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


